### PR TITLE
Pom cleanup

### PR DESCRIPTION
**Pull request by sgdc3**
Just the cleanup part of #9

### CODE REVIEW

**Comment by Steveice10** [comment]
Can you explain to me what these changes are for? For example, why the inclusion of the raven resources plugin when there are no resources to include, and why the removal of shading?

**Comment by Steveice10** [comment]
Actually, I can see why you would remove shading, but the rest I'm still unclear on the need for.

**Comment by sgdc3** [comment]
The resource plugin is called anyway by the maven default lifecycle, just to keep things updated.

**Comment by Steveice10** [comment]
Sure, but why explicitly include it in the pom? And why the rest of the changes?

**Comment by sgdc3** [comment]
to force it using the latest version of the plugin, since maven tends to use older versions by default

**Comment by Steveice10** [comment]
But again, what is the point of that if there aren't any resources anyway?

**Comment by sgdc3** [comment]
just good practice

**Comment by Steveice10** [comment]
Alright. It's not that big of a deal, I suppose. I'll be applying these changes to some of my other repositories as well later.

**Pull request merged**
