### PR TITLE
Stringified NBT

### PR DESCRIPTION
**Pull request by booleanbyte**
Adding capability of reading and writing stringified NBT from and to file and stream.

### CODE REVIEW

**Comment by Steveice10** [comment]
I've only given the code a cursory look-through so far, but is there a reason for the new interface instead of adding the string conversion methods to the Tag class? And also for not having destringify in CompoundTag.

**Comment by booleanbyte** [comment]
The reason I'm handling compound tag (and list tag) differently than the other tags is that I work with parsing compound tags and list tags from stream, in contrast to the other tags that hold specific values (and not other tags like compound or list tags do) from a string representing the tag that has already been completely read from the stream until the end of the tag (because simple values like float, double, and so on are identified at the end in snbt tag, so I needed the last character).
Compound tags can be recognized by the first character being '{', and list by the first 3 character starting with '[' and then not following the pattern of any array tag for the next 2 characters.
Array tags are a bit in between since they can be recognized by the first 3 characters, but I handle them as tags holding a value after recognizing them as not list to be consistent with the previous explanation.

**Comment by Steveice10** [comment]
Okay. As a more fundamental question, though, isn't the string representation of NBT usually just JSON? If so, wouldn't it be cleaner to just use an established JSON parser and convert the parsed result into NBT?

**Comment by booleanbyte** [comment]
SNBT looks very similar to JSON at first glance, so I've tried to represent NBT in JSON, but representing NBT in JSON is a horrible experience (talking from experience) since it's not not natively able to identify types like NBT tags that has an explicit way of identifying types beyond guessing what it could be like JSON does, since JSON is expecting the application to know exactly what type it's supposed to be.
And also Mojang has the brilliant idea of putting actual JSON in the string tags all over the place so it makes for a LOT of escaping quotes.

**Comment by Steveice10** [comment]
I will take a closer look and review when I have time over the weekend, then.

**Comment by booleanbyte** [comment]
So, after having had some more time away from working on it, and taking into account your first comment, I've managed to figure out a better way of reading that standardizes the destringify method to the tag class.

**Pull request merged**
